// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WbSailerNotifier.DataAccess.Context;

#nullable disable

namespace WbSailerNotifier.DataAccess.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241027192433_addAssemblyTask")]
    partial class addAssemblyTask
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("wb-sailer-notifier")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WbSailerNotifier.DataAccess.Models.AssemblyTask", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CargoType")
                        .HasColumnType("integer");

                    b.Property<int?>("ChrtId")
                        .HasColumnType("integer");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ConvertedCurrencyCode")
                        .HasColumnType("integer");

                    b.Property<int?>("ConvertedPrice")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CurrencyCode")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DTimeFrom")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DTimeTo")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ddate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeliveryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullAddress")
                        .HasColumnType("text");

                    b.Property<bool?>("IsNotified")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsZeroOrder")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("LatitudeAddress")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LongitudeAddress")
                        .HasColumnType("numeric");

                    b.Property<int?>("NmId")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Offices")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("OrderUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Price")
                        .HasColumnType("integer");

                    b.Property<List<string>>("RequiredMeta")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Rid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SalePrice")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ScanPrice")
                        .HasColumnType("numeric");

                    b.Property<List<string>>("Skus")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AssemblyTasks", "wb-sailer-notifier");
                });

            modelBuilder.Entity("WbSailerNotifier.DataAccess.Models.Order", b =>
                {
                    b.Property<string>("Srid")
                        .HasColumnType("text");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CancelDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("integer");

                    b.Property<decimal?>("FinishedPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("GNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("IncomeID")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsCancel")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsNotified")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsRealization")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsSupply")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("NmId")
                        .HasColumnType("integer");

                    b.Property<string>("OblastOkrugName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PriceWithDisc")
                        .HasColumnType("numeric");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Spp")
                        .HasColumnType("numeric");

                    b.Property<string>("Sticker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupplierArticle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Srid");

                    b.ToTable("Orders", "wb-sailer-notifier");
                });
#pragma warning restore 612, 618
        }
    }
}
