// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WbSailerNotifier.DataAccess.Context;

#nullable disable

namespace WbSailerNotifier.DataAccess.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("wb-sailer-notifier")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WbSailerNotifier.DataAccess.Models.Order", b =>
                {
                    b.Property<string>("Srid")
                        .HasColumnType("text");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CancelDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("integer");

                    b.Property<decimal?>("FinishedPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("GNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("IncomeID")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsCancel")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsNotified")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsRealization")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsSupply")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NmId")
                        .HasColumnType("integer");

                    b.Property<string>("OblastOkrugName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PriceWithDisc")
                        .HasColumnType("numeric");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Spp")
                        .HasColumnType("numeric");

                    b.Property<string>("Sticker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupplierArticle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Srid");

                    b.ToTable("Orders", "wb-sailer-notifier");
                });
#pragma warning restore 612, 618
        }
    }
}
